FILENAME="FreeRTOSv202406.01-LTS.zip"
URL="https://github.com/FreeRTOS/FreeRTOS-LTS/releases/download/202406.01-LTS/FreeRTOSv202406.01-LTS.zip"

TEMP_DIR="$(mktemp -d)"
OLD_OLDPWD="$OLDPWD"
OLD_PWD="$PWD"
cd "$TEMP_DIR"
curl -L "$URL" -o "$FILENAME"
unzip "$FILENAME"
mkdir -p "$OLD_PWD/lib"
mv "./FreeRTOS-LTS/FreeRTOS-Kernel" "$OLD_PWD/lib"
cd "$OLD_PWD"
OLDPWD="$OLD_OLDPWD"
rm -rf "$TEMP_DIR"
